name: Main CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  main-build-job:
    uses: n3oltd/actions/.github/workflows/n3o-dotnet-build-pack-push.yml@main
    with:
      nuget-packages: ''
      npm-packages: ''        
    secrets: inherit      
