name: Test PR

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: Test PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Test build website
        run: yarn build